---
name: POE-Component-IRC-Plugin-Syntax-Highlight-HTML
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: IRC plugin to highlight HTML code from URIs
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.005
  POE::Component::IRC::Plugin::OutputToPastebin: 0.001
  POE::Component::Syntax::Highlight::HTML: 0.0201
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::Syntax::Highlight::HTML:
    file: lib/POE/Component/IRC/Plugin/Syntax/Highlight/HTML.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
